<%= fetch(:rails_env) %>:
  adapter: postgresql
  timeout: 5000
  encoding: utf8
  reconnect: false
  database: ppagestores_production
  pool: 5
  username: ppagestores 
  password: ppagestores
  host:
  port: 5432